### ISSUE TITLE
感谢大兄弟 好人一生平安！

### ISSUE THREAD

**Issue by lndnxp** [out0fmemory/Goproxy-Always-Available#1]
(如果您是遇到本软件使用问题而并不清楚具体原因的话，请尽量提供更多信息，如软件版本，日志截图，地级运营商信息等。否则问题可能会被忽略或关闭)

“假如这里有坚固的高墙和撞墙破碎的鸡蛋，我总是站在鸡蛋一边。”

**Comment by goldenfreemanchina** [comment]
还以为您是另一只蛋。中间是不是还有个高个子的大兄第...

PS:是不是考虑关闭一下issues呢？
