### ISSUE TITLE
曲折玩活 R1632。。。

### ISSUE THREAD

**Issue by gjbg1989** [out0fmemory/Goproxy-Always-Available#21]
1、系统 IPv6 隧道工作正常
2、下载 R1632 并解压，貌似 goproxy-gui.exe 不支持32位系统，用 R1623/4 版32位替代
3、复制新版 XX-Net 压缩包内的 ip_range.txt （3个同名文件中的最大者）到程序目录下，改名为 iprange.conf
4、复制目录下 gae.json 为 gae.user.json ，编辑后者可添加私有 AppID
5、运行 goproxy-gui.exe ，数分钟后才能正常工作，生成非0大小的 google_ip.txt （程序启动会清空此文件）
6、复制 google_ip.txt 为 iprange.conf（冲抵旧文件）
😂 完成，下次启动应很快就会正常工作。

**Comment by RomanSmile** [comment]
@gjbg1989 
大神，今天又和你学到很多知识与技巧，希望多多发言以便提携我等小白学习！！！

**Comment by gjbg1989** [comment]
😱 程序员竟然在非程序员的老人面前自称小白。。。😭

**Comment by RomanSmile** [comment]
@gjbg1989 
你去下载r1623不要用r1632......r1623也就是phuslu社长删除项目时候最新的代码，然而r1632是out0fmemory重扛大旗编译的，他并没有什么改变，只是融合了gscan_quic扫描工具，速度快与慢全部关键都在ip上，你只要挑选很少有人用的1e100.net，填入几个健壮的，我的gop已经快两个月没有扫描更换ip了，速度依然，另外我不是什么程序猿，也是一个笨笨，只是摆弄时间久了，

**Comment by gjbg1989** [comment]
能写出 https://github.com/out0fmemory/Goproxy-Always-Available/issues/5 天书的还不是程序猿？
你只要挑选很少有人用的1e100.net ——不知1e100.net 是啥😂

**Comment by a250152** [comment]
时间一长就 no recent network activity.

**Comment by gjbg1989** [comment]
右键重启？

**Comment by a250152** [comment]
重启后过会  又完了

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8620 tertdo.bat 自动选用更好的服务器
或再重做第3、5及6步😱

**Comment by gjbg1989** [comment]
耍了近1小时，貌似仍然正常

**Comment by gjbg1989** [comment]
结束进程再启动。。。

**Comment by dahai058** [comment]
请教下在哪里下载 R1632文件  谢谢！

**Comment by whhxmwhh** [comment]
感谢！！请教一下这个项目的上传到服务器端的程序是哪一个？我有很久没有玩这个了。。这次的封锁太恐怖。我要多个梯子！～

**Comment by whhxmwhh** [comment]
https://github.com/goproxy0/goproxy/releases/tag/r1623

**Comment by whhxmwhh** [comment]
太感动了。最少是作为xx-net  ipv6的一种备用梯子。。感谢cctv。
最重要的是感谢gjbg1989

**Comment by whhxmwhh** [comment]
还有谷歌的坚持与执着！

**Comment by dahai058** [comment]
whhxmwhh   谢谢

**Comment by gjbg1989** [comment]
@dahai058 https://github.com/out0fmemory/Goproxy-Always-Available/releases

**Comment by gjbg1989** [comment]
@whhxmwhh goproxy-gae-server-r101.tar.xz

**Comment by gjbg1989** [comment]
64位系统有福了：https://gitter.im/gogotunnel/gogo 里的 fq.7z 😱

**Comment by dou4cc** [comment]
@gjbg1989 我刚刚删了

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8915 tertdo.bat自动或手动优选服务器

**Comment by a250152** [comment]
@gjbg1989 反应个BUG 时间一长后 teredo 会自动断开

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8961 或许有助稳定？

**Comment by whhxmwhh** [comment]
好像没有一个稳定的方法了。
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1632 (go/devel +b17470d Fri Oct 13 06:48:36 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "read udp: NetworkIdleTimeout: No recent network activity."

**Comment by gjbg1989** [comment]
天书😂

**Comment by endlessX** [comment]
没必要这么麻烦，直接把XX-NET扫出来的IP拷进GOPROXY就能用，速度比XX-NET快得多

**Comment by out0fmemory** [comment]
为什么最近这段时间没有维护，就是看到有人说因为我这个项目很多可用ip被封。。。。。
所以，我准备停一段时间看看，哦呵呵呵呵！！！！

**Comment by gjbg1989** [comment]
😱接盘侠驾到😂

**Comment by whhxmwhh** [comment]
折騰能用就是好。只是多個備用的梯子！～感謝。

**Comment by xrwz007** [comment]
@gjbg1989 請問如何把類似如下：“
2404:6800:400c:9::b r5---sn-i3beln7k.googlevideo.com gws 300 0
2404:6800:400c:9::a r4---sn-i3beln7k.googlevideo.com gws 300 0
2404:6800:4005:11::9 r3---sn-i3belnez.googlevideo.com gws 300 0
2404:6800:400b:1d::9 r4---sn-oguesnlz.googlevideo.com gws 300 0
2404:6800:400b:28::7 r1---sn-oguesnsy.googlevideo.com gws 300 0
2404:6800:400c:4::8 r2---sn-i3b7kn76.googlevideo.com gws 300 0
v6地址複製到goproxy 裡去？或者說哪個文件裡去才能識別？

**Comment by gjbg1989** [comment]
唔知😂

**Comment by gjbg1989** [comment]
2404:6800:400c:9::b|2404:6800:400c:9::a|2404:6800:4005:11::9|2404:6800:400b:1d::9|2404:6800:400b:28::7|2404:6800:400c:4::8
首先排列如上格式并全部复制，运行 goproxy ，在浏览器内打开 http://127.0.0.1:8087/ip.html ，左键左边窗口、右键粘贴，点选 IPv6 ，点击“写入到本 地json 文件”，完成。
貌似 @endlessX 说的“直接把XX-NET扫出来的IP拷进GOPROXY就能用”就是如此？

**Comment by gjbg1989** [comment]
开机启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by gjbg1989** [comment]
运行 XX-NET 导出 IP ，全选、复制，结束进程 pythonw.exe，运行 goproxy ，在浏览器内打开 http://127.0.0.1:8087/ip.html ，左键左边窗口、右键粘贴，点选 IPv6 ，点击“写入到本地 json 文件”，完成。R1624 也有效😱

**Comment by xrwz007** [comment]
@gjbg1989 感謝詳盡解答

**Comment by szwuzy** [comment]
3.9.6 IPV6 确实能用，但速度非常有限。。。。 
不知调节manual.ini是否能有改善！！！请问各位大佬。

下面是youtube的显示连接速度详细。
Current / Optimal Res256x144@24 / 1280x720@24
Volume / Normalized100% / 100%
Codecsvp9 (278) / opus (251)
Hostr6---sn-vgqsenls
Connection Speed68 Kbps
Network Activity0 KB
Buffer Health333.11 s
Dropped Frames

**Comment by gjbg1989** [comment]
No Coin 免費擴充功能下載，阻擋網站挖礦程式消耗你的硬體資源 - https://wp.me/p4CzB-hd7 by @pseric on @FreeGroup

**Comment by gjbg1989** [comment]
系统 IPv6 隧道工作正常，Mini 有效 https://github.com/xyuanmu/XX-Mini
