### ISSUE TITLE
大家的还依然坚挺吗?

### ISSUE THREAD

**Issue by a250152** [out0fmemory/Goproxy-Always-Available#32]
是否就我一个人挂了?

**Comment by gjbg1989** [comment]
系统 IPv6 正常，貌似 XX-Net XX-Mini 更坚挺😂

**Comment by a250152** [comment]
@gjbg1989 xxnet 可以但是goproxy不行了
xxnet 不能登录google账户

**Comment by gjbg1989** [comment]
xxnet 完全登录google账户，或使用 X-Tunnel自动切换 模式

**Comment by a250152** [comment]
@gjbg1989 升级10.8可以了 但是goproxy这么好的项目要弃 挺可惜啊 -_-
